version: '3.9'

services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:docker
    environment:
      PORT: 5000
      DATABASE_URL: postgres://docker:password@db/docker
      JWT_KEY: jwtkey
    depends_on:
      - db

  db:
    image: 'postgres'
    ports: 
      - '4321:5432'
    environment:
      POSTGRES_DB: docker
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: